### ISSUE TITLE
KorGW Documentation

### ISSUE THREAD

**Issue by reymalahay** [soywiz-archive/korgw#42]
Hi all,

Is there a plan to release documentation for `KorGW`? I am looking for information on how to use `KorGW` with conventional `Android` classes.

Please advise.

Thanks in advance,
rey malahay

**Comment by soywiz** [comment]
KorGW is not directly supported, only KorGE is supported. If you want to use korgw directly, I'm afraid you are on your own.
As instructed in the other issue, please for this kind of thing, use https://discord.korge.org/ or the https://forum.korge.org/ .

I'm closing this issue.
